name: DEV (pull request) - Build

on:
 pull_request:
   branches:
     - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
     matrix:
      node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
       node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      working-directory: ./backend
      run: npm i
    - name: Tests
      working-directory: ./backend
      run: npm run test
